CREATE TABLE TASK
(
    TASK_ID BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DESCRIPTION TEXT NOT NULL,
    TASK_STATUS_CODE CHAR(3) NOT NULL
);

CREATE TABLE TASK_STATUS
(
    TASK_STATUS_CODE CHAR(3) PRIMARY KEY NOT NULL,
    TASK_STATUS_NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(200) NOT NULL,
    DISPLAY_ORDER INT(11) NOT NULL
);

ALTER TABLE TASK
ADD CONSTRAINT FK_TASK_TASK_STATUS_TASK_STATUS_CODE
FOREIGN KEY (TASK_STATUS_CODE) REFERENCES TASK_STATUS (TASK_STATUS_CODE);